@echo off

set TEST_LOG=%CLI_OUT_DIR%\preencbat.log

echo test > "%TEST_LOG%"

echo %CLI_IN_PATH%                 >> "%TEST_LOG%"
echo %TS_IN_PATH%                  >> "%TEST_LOG%"
echo %TS_IN_DIR%                    >> "%TEST_LOG%"
echo %CLI_OUT_DIR%                 >> "%TEST_LOG%"
echo %OUT_DIR%                      >> "%TEST_LOG%"
echo %SERVICE_ID%                  >> "%TEST_LOG%"
echo %CLI_OUT_PATH%                >> "%TEST_LOG%"
echo %IMAGE_WIDTH%                 >> "%TEST_LOG%"
echo %IMAGE_HEIGHT%                >> "%TEST_LOG%"
echo %SERVICE_ID%                  >> "%TEST_LOG%"
echo %AMT_ENCODER%                 >> "%TEST_LOG%"
echo %AMT_AUDIO_ENCODER%           >> "%TEST_LOG%"
echo %AMT_TEMP_DIR%                >> "%TEST_LOG%"
echo %AMT_TEMP_AVS%                >> "%TEST_LOG%"
echo %AMT_TEMP_AVS_TC%             >> "%TEST_LOG%"
echo %AMT_TEMP_AVS_DURATION%      >> "%TEST_LOG%"
echo %AMT_TEMP_AFS_TC%             >> "%TEST_LOG%"
echo %AMT_TEMP_VIDEO%              >> "%TEST_LOG%"
echo %AMT_TEMP_AUDIO%              >> "%TEST_LOG%"
echo %AMT_TEMP_AUDIO_0%            >> "%TEST_LOG%"
echo %AMT_TEMP_AUDIO_1%            >> "%TEST_LOG%"
echo %AMT_TEMP_CHAPTER%            >> "%TEST_LOG%"
echo %AMT_TEMP_TIMECODE%           >> "%TEST_LOG%"
echo %AMT_TEMP_ASS%                >> "%TEST_LOG%"
echo %AMT_TEMP_ASS_0%              >> "%TEST_LOG%"
echo %AMT_TEMP_ASS_1%              >> "%TEST_LOG%"
echo %AMT_TEMP_SRT%                >> "%TEST_LOG%"
echo %AMT_TEMP_SRT_0%              >> "%TEST_LOG%"
echo %AMT_TEMP_SRT_1%              >> "%TEST_LOG%"
echo %AMT_TEMP_ASS_NICOJK_720S%   >> "%TEST_LOG%"
echo %AMT_TEMP_ASS_NICOJK_720T%   >> "%TEST_LOG%"
echo %AMT_TEMP_ASS_NICOJK_1080S%  >> "%TEST_LOG%"
echo %AMT_TEMP_ASS_NICOJK_1080T%  >> "%TEST_LOG%"
