name: Docker build test

on:
  push:
    branches:
    - master
    - linux

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker info
        run: |
          docker version
          docker info

      - name: Prepare working dirs via setup.sh
        working-directory: docker
        run: |
          chmod +x ./setup.sh
          ./setup.sh

      - name: Install yq
        run: |
          YQ_VERSION=v4.44.3
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Disable GPU-related blocks in compose.yml (safe delete)
        working-directory: docker
        run: |
          yq -i 'del(.services.amatsukaze.devices, .services.amatsukaze.deploy)' compose.yml
          echo "== composed compose.yml =="
          sed -n '1,200p' compose.yml

      - name: Build images with docker compose
        working-directory: docker
        run: |
          docker compose build


